name: Maven Test Automation Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Run Selenium Tests
        run: mvn clean test

      - name: Generate Allure Report
        uses: allure-framework/allure-report@v0
        with:
          results-directory: target/allure-results
          report-directory: target/allure-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allure-cli-version: 2.30.0

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report
